(chore): update tailwind to v3
Vizzuality/front-end-scaffold pull request #49
Opened 2022-04-13 20:28 UTC by anamontiaga

In addition to updating the latest version and plugins, the following changes have been made:

- [ ] Update some specific colors (_green, yellow, purple and gray)_
- [ ] Update flex-grow and flex-shrink to new naming
- [ ] Remove `theme` and `variants` by default as there are no longer needed (on V3 everything is enabled by default)
- [ ] Remove `purge` (is no longer needed to remove unused styles)

2022-04-21 09:22 UTC, mbarrenechea requested changes
Pakages:
Don't use latest as the version to use

Colors:
Instead of changing all the classnames in the components it would be better if you add the colors inside the config

```
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    extend: {
      colors: {
        gray: colors.slate,
        green: colors.emerald,
        yellow: colors.amber,
        purple: colors.violet,
      }
    },
  },
  // ...
}
```

2022-04-21 09:22 UTC, mbarrenechea commented on components/confirmation-prompt/component.tsx
> +          <Icon icon={icon} className="flex-grow hidden ml-auto sm:block flex-shrink-1 w-36" />
```suggestion
          <Icon icon={icon} className="grow-1 hidden ml-auto sm:block shrink-1 w-36" />
```

2022-05-04 14:34 UTC, anamontiaga commented
> Pakages: Don't use latest as the version to use
> 
> Colors: Instead of changing all the classnames in the components it would be better if you add the colors inside the config
> 
> ```
> const colors = require('tailwindcss/colors')
> 
> module.exports = {
>   theme: {
>     extend: {
>       colors: {
>         gray: colors.slate,
>         green: colors.emerald,
>         yellow: colors.amber,
>         purple: colors.violet,
>       }
>     },
>   },
>   // ...
> }
> ```

Why rename the colors and not adapt to the new names if we are going to use the scaffold for new projects?

2022-05-05 10:18 UTC, anamontiaga commented
Soved in [https://github.com/Vizzuality/front-end-scaffold/pull/53](https://github.com/Vizzuality/front-end-scaffold/pull/53)

2022-05-05 10:18 UTC, closed without merging